stages:
  data_ingestion:
    cmd: python scripts/data_ingestion.py
    deps:
      - data/raw/
    outs:
      - data/preprocessed/
  data_preprocessing:
    cmd: python scripts/data_preprocessing.py
    deps:
      - data/preprocessed/
    outs:
      - data/preprocessed/cleaned/
